### ISSUE TITLE
New target_type structure

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#115]
Hello,

We are using `target_type` (from [core/targets.py](https://github.com/zdresearch/OWASP-Nettacker/blob/master/core/targets.py#L32)) to define the target type (`HTTP`, `SINGLE_IPv4`, `SINGLE_IPv6`, `RANGE_IPv4`, etc...). 

It's best to improve the URL section to detect the URL types such as (`ssh`, `ftp`, `smtp`, etc..) to make it work better!

Regards.

**Comment by VictorSuraj** [comment]
Means like "ftp://<website>". So that our scanning and bringing data from 21 port is specially targeted.

**Comment by VictorSuraj** [comment]
an example ==>   ftp://linux.org.

**Comment by Ali-Razmjoo** [comment]
Hey,

Yes, I meant like `ftp://anywebsite` or `ftp://anywebsite:5000` to specify the port.

Regards.
