### ISSUE TITLE
Better Help Menu

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#116]
Hello,

As you can see, by adding modules, help menu begin really complicated and big with many listed modules to select or exclude! I think we've re-build this section.

Regards.

**Comment by pradeepjairamani** [comment]
Hello,

I think it can be solved by solving issue #97 (Joining multiple vulnerability scanner)

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey @pradeepjairamani,

Thanks for informing, I think it's helping but it still needs to be better! we can combine some of the modules but we will grow with unique modules in future, that will drive us to this problem again.

Regards.

**Comment by pradeepjairamani** [comment]
Hello,

Yes that's true, we can create scan mode search like `vuln` `scan` `all` etc instead of showing it in the help menu and user will search according to that and we also need to implement autocomplete for modules.

Best Regards

**Comment by Ali-Razmjoo** [comment]
Hey,

Autocomplete could be add in wizard mode #117. thanks for the idea.

Regards.

**Comment by aman566** [comment]
I would like to work on it. Please assign this to me @Ali-Razmjoo .
