### ISSUE TITLE
Interactive Wizard Mode

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#117]
Hello,

Currently, we have simple wizard mode (`-w`/`--wizard` switch #5) to make scanning progress easier for users in command line interface, it's working but it's great! I am thinking about something better or interactive, let me know if you've any ideas.

Best Regards.

**Comment by shaddygarg** [comment]
Why don't we make a similar interface to that of OWASP ZSC. I love its simplicity and the ease to work with it?

**Comment by Ali-Razmjoo** [comment]
@shaddygarg thanks for referring, I just want to see if we've better options! e.g. sqlmap hast am easy and clear wizard!

Regards.
