### ISSUE TITLE
Security issue (try, except, pass)

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#119]
Hello,

We've used many try, except, pass in our code and after I read the project review from codacy, I've to notice that it's a low-risk [security issue](https://docs.openstack.org/bandit/latest/plugins/b110_try_except_pass.html). 

Regards.

**Comment by shaddygarg** [comment]
I think we should log all the exceptions in a temporary file that gets deleted, once the scan is complete.

**Comment by Ali-Razmjoo** [comment]
Thanks @shaddygarg for sharing your idea, let's see if anyone else has any idea.

Regards.
