### ISSUE TITLE
Bring ML to OWASP Nettacker

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#121]
Hello,

As you know, OWASP Nettacker logs every event in the database, after a while, you will have enough data to use them for machine learning to find the risks easier. I am not an expert in AI/ML so I cannot tell, but I have a few ideas. for instance, we have a company with an internal network (include 10,000 IPs), I can tell it's easy to set a cronjob and analysis the network hourly, but it's a little bit hard to monitor the events! that's where I would like to use ML to create diagrams/charts to monitor the events in WebUI. To be sure if it's possible and this theory is not wrong, I will ask Dr. Vahid Behzadan (@behzadanksu) to guide us in this case and will let you know the updates.

I know we can do better with the data, so I am glad to send me your ideas to work on.

Best Regards.

**Comment by shaddygarg** [comment]
I also don't know much about it but for applying any kind of ML will require a large dataset and that will not be suitable for more common users. What will we do for the users with very less data. Are we focussing more on developing for large organisations?

**Comment by Ali-Razmjoo** [comment]
Thanks for mentioning that, I think it would be a good feature for large scale companies, it could be work on smaller dataset, but it has much false positive, we should think for all users, the large companies are also are in our list.

Regards.

**Comment by behzadanksu** [comment]
In general, the answer to how much or what type of data is required depends on what exactly do you expect of your models. Do we have any clear ideas on what we want our ML models to do? Even if you don't have any, I'd be happy to hear your thoughts and ideas for potential applications of ML in Nettacker.

**Comment by Ali-Razmjoo** [comment]
Hey @behzadanksu , Thanks for your reply,

I don't have a clear idea, but I expect to monitor the network and find the risks easier with the ML, we already have a WebUI that helps developers to search for specific information, but for large-scale companies, we will have many events that we don't know which one has the highest risk, sometimes it could be boring to look into the all of the events to find **uncommon** one, especially when it contains information gathering events!

So as our first idea to start bringing ML into this framework, could it be the idea of finding uncommon events between others? I think ("think") it could be good idea for two reasons, first, it's not in the offensive (but I think it could be :-?), second it's easier to start.


Thanks for your time, looking forward to hearing from you and all other contributors.

Best Regards.

**Comment by Tikam02** [comment]
@Ali-Razmjoo this summer I  did my internship in company with applied deep learning and machine learning. This is my work https://github.com/Tikam02/Crowd_Estimation_DeepLearning
And I have some research papers based on network monitoring and some security based, yet to be implemented.
It'll be great to blend MachineLearning+DeepLearning+Cyber Security.

**Comment by Ali-Razmjoo** [comment]
@Tikam02 sorry for late response, 

great! I will contact you within a few days (I am really busy now with work) and we will discuss it.
