### ISSUE TITLE
OWASP Nettacker Project UML

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#125]
Hello,

Since the project is growing, I think wiki it's not enough for developers to get to know the project, of course, they can learn about the project, but it's best to spend less time on studying the project, that's why I want to suggest to start creating a UML.

* We can create UML using JS libraries and JSON structure, and whenever it's updated we read it from GitHub and showing it online on a website

feel free to share your ideas regarding this.

Best Regards.

**Comment by shaddygarg** [comment]
Hey @Ali-Razmjoo, 
Can you elaborate on this? Do you want to create a diagram of sorts which is self-updating whenever a new commit is pushed onto Github and gives information about the directory structure and what each directory does or you want something else? Do you have an example of this kind of implementation?
Best Regards.

**Comment by shaddygarg** [comment]
@Ali-Razmjoo, any thoughts on this??

**Comment by Ali-Razmjoo** [comment]
we can add something with graphviz later if needed.
