### ISSUE TITLE
Clean Code

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#135]
Hey,

I found a few cool references to explain the clean-code in python. We already implementing base on them but we miss a few sections! it will be awesome to review the code and clean up what we missed!

* fix conditions 
* fix names
* remove duplicates and repeated code
* code-based documentions
* PEP8
* etc.

Regards.

## Refrences
* https://github.com/zedr/clean-code-python
* https://github.com/rmariano/Clean-code-in-Python/blob/master/build/Clean%20code%20in%20Python.pdf

**Comment by abhisharma404** [comment]
@Ali-Razmjoo Hey there! I would like to work on this.

**Comment by Ali-Razmjoo** [comment]
@abhisharma404 thanks, I will check your PR soon.
