### ISSUE TITLE
Implement new HTTP Fuzzer into HTTP-Based modules

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#150]
Hello,

Now we have a simple HTTP Fuzzer/Repeater [available](https://github.com/zdresearch/OWASP-Nettacker/pull/147/) in the framework that could help us to remove duplicate codes, please consider the `pma_scan` module as an example of implementing of this fuzzer. The documentation is also available in code, readme file. (and will be avalaibe in wiki soon)

Regards.

**Comment by shaddygarg** [comment]
Hey,
The wiki is now avaliable [here](https://github.com/zdresearch/OWASP-Nettacker/wiki/Developers#adding-a-fuzzing-module-owasp-nettacker-http-fuzzer-module-usage). In case of any confusion, I am always ready to help.
Regards.

**Comment by Ali-Razmjoo** [comment]
Thanks @shaddygarg.
