### ISSUE TITLE
Issue in getting results via discovery funstion in service scanner

### ISSUE THREAD

**Issue by shaddygarg** [OWASP/Nettacker#171]
I was trying to perform the same operation on my localhost and results were different everytime.
```python
In [1]: from lib.payload.scanner.service.engine import discovery

In [2]: discovery("127.0.0.1")
Out[2]: {443: 'UNKNOWN', 3306: 'UNKNOWN'}

In [3]: discovery("127.0.0.1")
Out[3]: 
{80: 'http',
 443: 'UNKNOWN',
 631: 'UNKNOWN',
 3306: 'UNKNOWN',
 5432: 'UNKNOWN',
 8002: 'http'}

In [4]: discovery("127.0.0.1")
Out[4]: 
{80: 'http',
 139: 'UNKNOWN',
 443: 'UNKNOWN',
 445: 'UNKNOWN',
 631: 'UNKNOWN',
 3306: 'UNKNOWN',
 5432: 'UNKNOWN',
 8001: 'UNKNOWN',
 8002: 'http'}

In [5]: discovery("127.0.0.1")
Out[5]: 
{80: 'http',
 139: 'UNKNOWN',
 443: 'UNKNOWN',
 445: 'UNKNOWN',
 631: 'UNKNOWN',
 3306: 'UNKNOWN',
 5432: 'UNKNOWN',
 8001: 'UNKNOWN',
 8002: 'http'}
```
![image](https://user-images.githubusercontent.com/21990986/41881942-d63dc2ea-7903-11e8-87a5-5084c6e74d16.png)

Am I doing anything wrong or is it some problem with the module!! Performing a port scan however works fine for me.
_________________
**OS**: `Ubuntu`

**OS Version**: `16.04`

**Python Version**: `2.7.12`

**Comment by pradeepjairamani** [comment]
Thanks for the issue @shaddy I will solve this ASAP

Best Regards
Pradeep Jairamani

**Comment by Ali-Razmjoo** [comment]
I think it's just because of the timeout... do you have any solution @pradeepjairamani ?

**Comment by pradeepjairamani** [comment]
I am currently working on the solution, I think changing this below line can solve the issue.

`if threading.activeCount() is 1 or int(kill_switch) is int(timeout * 5 * 10):`

Best Regards

**Comment by Ali-Razmjoo** [comment]
i think this issue is duplicated with #101

**Comment by shaddygarg** [comment]
Yes, I also think it is related to the same.

**Comment by Ali-Razmjoo** [comment]
so until we don't have a good solution, increase the timeout a little bit! :D

**Comment by aman566** [comment]
In my machine for the very first time when I are running it, I am still able to reproduce the issue.

![image](https://user-images.githubusercontent.com/32503192/83988930-65ead780-a962-11ea-8eb6-af1e38f8662b.png)

**Comment by aman566** [comment]
We need to still increase the timeout a little bit: from **5*10** to **9*10**.

**Comment by Captain-K-101** [comment]
Hello
i would like to take up this issue if its still unresolved + wont it be better to map the custom ports to the services which usually use it
ie right now 3306 is showing "UNKNOWN" but usually mysql runs on it  right. so rather than saying UNKNOWN i wont it be better to show *mysql(* as in may be present).
