### ISSUE TITLE
Nonworking languages

### ISSUE THREAD

**Issue by cwcromwell** [OWASP/Nettacker#181]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `macOS` 

**OS Version**: `10.11.6`

**Python Version**: `3.6.1`

The language command line flag is not working for Pashto. The input `python3 nettacker.py -L ps` results in the following error: 

```
Traceback (most recent call last):
  File "nettacker.py", line 13, in <module>
    load()  # load and parse the ARGV
  File "/Applications/OWASP-Nettacker-master/core/parse.py", line 34, in load
    module_names, graph_names)
  File "/Applications/OWASP-Nettacker-master/core/args_loader.py", line 117, in load_all_args
    help=messages(language, "select_profile").format(_all_profiles))
ValueError: Single '}' encountered in format string

```

**Comment by Ali-Razmjoo** [comment]
Hi @cwcromwell thanks for reporting, 

@pradeepjairamani please take a look and send the patch. let me know if you have any questions.

Regards.

**Comment by pradeepjairamani** [comment]
@Ali-Razmjoo I will have a look into it

**Comment by Ali-Razmjoo** [comment]
Hi, should I close this one?
