### ISSUE TITLE
Fixes for the "Usage" section of docs wiki

### ISSUE THREAD

**Issue by cwcromwell** [OWASP/Nettacker#182]
I did a basic line edit of the "Usage" section, but next it needs reorganization and more information. 

Would anyone want to spend time on a call or two to help me understand some of the commands? Some of them aren't obvious to me from the command line help, so they might benefit from better explanation.

(I'll continue to work on this section, but having a technical expert to answer some of the questions would be great.)

I think this section would work better by expanding and re-organizing, with the following outline: 

USAGE 

1.) The setup commands  (with a description and example for each)
-language
-verbosity 
- version
- update 
- log in file
- graph 
- help
- wizard 
- profile

2.) Basic command usage
- The base syntax of CLI commands (nettacker -i <targets> -m <methods>)
-Everything you need to know about the targets-related commands (including lists)
-Everything you need to know about the methods-related commands (such as excluding)

3.) More advanced commands 
- users
- users_list
- passwords
- passwords_list
- ports
- timout
- time_sleep
- range
- subdomains
- thread number
- thread_number_host
- socks_proxy
- retries
- ping_before_scan
- methods_args
- methods_args_list

**Comment by shaddygarg** [comment]
Hey @cwcromwell. It would be really good if you talk to one of us. I am sure @Ali-Razmjoo won't mind scheduling a call with you but if he is busy, I am available. Just ping me a time and date and we can get things started.

**Comment by Ali-Razmjoo** [comment]
Hi,

sorry for delay, I'm on trip until tomorrow night, after that will be free too. we have a slack group, and I am also available on skype and hangsout,

so just let me know the schedule I will glad to help.

Best Regards.

**Comment by cwcromwell** [comment]
Cool. Would a weekend call be okay? My availability to work on things is best on Saturday and Sunday. Also, please let me know your time zones, guys.

**Comment by Ali-Razmjoo** [comment]
I will add you to slack channel tomorrow for farther schedules, I'm free on weekends.

**Comment by Ali-Razmjoo** [comment]
Hi Clarence, I've sent you an invitation to our Slack,
