### ISSUE TITLE
core>targets.py  bug

### ISSUE THREAD

**Issue by aliluyala** [OWASP/Nettacker#185]
the method "target_type" in core>targets.py  can‘t distinguish some targets like this "Publish_server.oa.xxx.com"。

 I think the right code should be：

`def target_type(target):
    ...
    
    elif re.match('^([a-zA-Z0-9]+(-|_[a-zA-Z0-9]+)*\.?)+[a-z]{2,}$', target):
        return 'DOMAIN'
    elif (target.lower().startswith('http://') or target.lower().startswith('https://')):
        t = target.rsplit("://")[1].rsplit("/")[0].rsplit(":")[0]
        if isIP(t) or isIP6(t) or re.match('^([a-zA-Z0-9]+(-|_[a-zA-Z0-9]+)*\.?)+[a-z]{2,}$', t):
            return 'HTTP'
    elif len(target.rsplit('.')) is 4 and '-' not in target and '/' in target:
        IP, CIDR = target.rsplit('/')
        if isIP(IP) and (int(CIDR) >= 0 and int(CIDR) <= 32):
            return 'CIDR_IPv4'
    return 'UNKNOWN'`
_________________
**OS**: `windows`

**OS Version**: `10`

**Python Version**: `python 2.7.15

**Comment by Ali-Razmjoo** [comment]
Thanks for reporting the bug @aliluyala, I will fix it soon.
Regards.
