### ISSUE TITLE
Using socks proxy template as python decorator

### ISSUE THREAD

**Issue by abhisharma404** [OWASP/Nettacker#187]
We can use the socks proxy template as a python decorator, instead of repeating the following code every time we can just use a decorator, for e.g. `@socks_proxy` over every function that needs it.

codes...

            if socks_proxy is not None:
                socks_version = socks.SOCKS5 if socks_proxy.startswith('socks5://') else socks.SOCKS4
                socks_proxy = socks_proxy.rsplit('://')[1]
                if '@' in socks_proxy:
                    socks_username = socks_proxy.rsplit(':')[0]
                    socks_password = socks_proxy.rsplit(':')[1].rsplit('@')[0]
                    socks.set_default_proxy(socks_version, str(socks_proxy.rsplit('@')[1].rsplit(':')[0]),
                                            int(socks_proxy.rsplit(':')[-1]), username=socks_username,
                                            password=socks_password)
                    socket.socket = socks.socksocket
                    socket.getaddrinfo = getaddrinfo
                else:
                    socks.set_default_proxy(socks_version, str(socks_proxy.rsplit(':')[0]),
                                            int(socks_proxy.rsplit(':')[1]))
                    socket.socket = socks.socksocket
                    socket.getaddrinfo = getaddrinfo
codes ...

This would reduce the code duplication and the effort to use the above code. Moreover it would help in code-re-usability.
_________________
**OS**: `Kali Linux`

**OS Version**: `2`

**Python Version**: `3.6`

**Comment by abhisharma404** [comment]
Another option could to be to put the socks proxy template in a function, import and call that function whenever needed.

Any suggestions?

**Comment by Ali-Razmjoo** [comment]
we need to think about fully restructuring this.
