### ISSUE TITLE
[Low] Unmet dependencies in requirements.txt

### ISSUE THREAD

**Issue by 0xInfection** [OWASP/Nettacker#244]
There are some unmet dependencies in the `requirements.txt`:
- The module under `brute/http_ntlm` uses the `pycurl` library.
- The module under `payload/scanner/ics_honeypot` uses the `xmltodict` library.

Both of which are not marked as dependencies in the `requirements.txt`.
_________________
**OS**: `Ubuntu`

**OS Version**: `18.04`

**Python Version**: `3.6`

**Comment by securestep9** [comment]
There was an attempt to get rid of pycurl which was originally heavily used, removed from requirements.txt a bit early

**Comment by 0xInfection** [comment]
Hey @securestep9, thanks for your insight. :)

Do you think I should rewrite the code using the `requests-ntlm` library for bruteforcing NTLM authentication? If yes, I will be more than happy to contribute.

**Comment by securestep9** [comment]
Hey @0xInfection - all contributions are welcome. If you are going to write a new module it's best to have a different module name and perhaps you can come up with more features
