### ISSUE TITLE
Error running maltego transforms

### ISSUE THREAD

**Issue by aman566** [OWASP/Nettacker#275]
The steps give in maltego usage in the documentation is followed but the command:
`canari create-profile nettacker_transforms -w {ABSOLUTE PATH OF DIRECTORY}/OWASP-Nettacker/lib/transactions/maltego/nettacker_transforms/src`

Giving this error:
```
Loading Canari configuration file '/home/am4n/.canari/canari.conf'
Usage: canari create-profile [OPTIONS] [PACKAGE]
Try 'canari create-profile --help' for help.
```
This is my .canari/canari.conf file:
```
[canari.local]
# Additional config files that should be read to merge with the current config
configs =

path = ${PATH},/usr/local/bin,/opt/local/bin

[canari.remote]
# This section deals exclusively with remote transform execution and has no effect on local transform execution. Modify
# these options if you are running your transforms under plume.

# Additional config files that should be read to merge with the current config in remote exec mode.
configs =

# Specify any transforms that your WSGI container will host. This is for Plume ONLY.
packages =

path = ${PATH},/usr/local/bin,/opt/local/bin
```
Something is going wrong with my canari.conf file I think. This issue will come whenever someone freshly clone the repo and follow the [maltego transforms](https://github.com/zdresearch/OWASP-Nettacker/wiki/Usage#maltego-transforms)
_________________
**OS**: `Linux`

**OS Version**: `Ubuntu 18.04`

**Python Version**: `3.6.9`

**Comment by Ali-Razmjoo** [comment]
ditched in new version
