### ISSUE TITLE
False Positives while running dir_scan

### ISSUE THREAD

**Issue by aman566** [OWASP/Nettacker#280]
The current version of Nettacker scans for directory listing. But doing directory listing it searches for 401, 403, 200 status codes which is really a good approach. But in this manner what happens is many websites(90% where I used the tool) smartly creates some 404 pages where the status codes are 200 which is really bad for the tool giving false positives.
![image](https://user-images.githubusercontent.com/32503192/83360601-1162bd80-a3a0-11ea-8ea2-3c45b8a3b515.png)

_________________
**OS**: `Linux`

**OS Version**: `Ubuntu 18.04`

**Python Version**: `3.6.9`

**Comment by 0xrishabh** [comment]
I don't think there's any way to deal with this situation, other than to use `ffuf` which gives you the option to auto-calibrate false positive and removes them.

**Comment by itsdivyanshjain** [comment]
We can reduce the false positive by checking the title and meta tags of html files which contains keywords like 404,not found, etc... As most html returned 404 pages with status 200 follows the same pattern. This may reduce false positive in a significant manner.
