### ISSUE TITLE
Tool running Wordpress Modules on a domain which does not support Wordpress

### ISSUE THREAD

**Issue by aman566** [OWASP/Nettacker#318]
If a website is made over WordPress then only it should check for wp-user-enum, wp-plugins, wp-themes.
Websites that are not built on WordPress, the tool should skip those checks.

It will affect and time will be wasted if we use **-s** for scanning all subdomains because in that case WordPress modules will be checked on all subdomains and not every subdomain will be made on WordPress in normal cases.

The tool should first check the cms it is using by calling wappalyzer or whatcms modules and then detect if any WordPress cms is present or not. If it has cms then it should go for WordPress modules, else should skip that subdomain for WordPress checks.

![image](https://user-images.githubusercontent.com/32503192/86726448-3229cd00-c048-11ea-8aeb-72431ef15eca.png)

_________________
**OS**: `Linux`

**OS Version**: `Ubuntu 18.04`

**Python Version**: `3.6.9`

**Comment by securestep9** [comment]
@aman566 - this is a good feature request suggestion, however with less priority. I would expect that the users will run CMS-specific scans (WordPress/Joomla/Drupal) only after confirming the actual CMS using cms_detection_scan module, wappalyser or whatcms (for Internet-facing sites) for now. We can (and we definitely should) implement this, but a bit later

**Comment by aman566** [comment]
Yes sure.
