### ISSUE TITLE
Internal server error with docker

### ISSUE THREAD

**Issue by akashtalole** [OWASP/Nettacker#360]
I hvae cloned git repo and build docker image. Then ran docker-compose up. When I access https://127.0.0.1:5000/ it gives internal server error and below error on command line 

`nettacker_1  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 36457: ordinal not in range(128)`
_________________
**OS**: `Ubuntu`

**OS Version**: `20.04`

**Python Version**: `2.7`

**Comment by itsdivyanshjain** [comment]
This docker image pulls python2.7 which is leads to UnicodeDecodeError when it start the api (issue same as #359 ). Soon this issue going to be solved until before that use this tool with python3.

**Comment by securestep9** [comment]
hi @akashtalole  this has been fixed now and tested to work fine in Ubuntu 20.04 please try to do a fresh git clone and docker-compose up

**Comment by securestep9** [comment]
fixed in PR #359

**Comment by akashtalole** [comment]
Thanks working now.
