### ISSUE TITLE
Error while running the dir_scan module

### ISSUE THREAD

**Issue by ktg-123** [OWASP/Nettacker#388]
This error occurred while running the dir_scan module

![bug](https://user-images.githubusercontent.com/58258464/107110398-81014480-686d-11eb-9d11-d4ce8a5ad14b.png)

_________________
**OS**: `Ubuntu`

**OS Version**: `18.04`

**Python Version**: `3.6.9`

**Comment by aman566** [comment]
In Macos It's running all good.
Will verify in linux.

**Comment by ktg-123** [comment]
In my case when the result during the scan is quite large this error is thrown. Otherwise for normal scans, it's working fine.

**Comment by securestep9** [comment]
this is a multi-threading issue - is this happening on mysql as well?

**Comment by ktg-123** [comment]
No @securestep9, I am unable to reproduce this issue using mysql
