### ISSUE TITLE
port_scan module not working in Python 3.9

### ISSUE THREAD

**Issue by securestep9** [OWASP/Nettacker#398]
in python 3.9.1 getting error:

 [X] this module "port_scan" is not available.

Probably some incompatibilities in Python 3.6->3.9 are crashing the module 
_________________
**OS**: `Kali.Linux`

**OS Version**: `2020.3`

**Python Version**: `3.9.1`

**Comment by itsdivyanshjain** [comment]
I would like to take up this issue

**Comment by aman566** [comment]
In python 3.9.0 It's working fine after installing scapy properly.
`[X] this module "port_scan" is not available.` is due to scapy

**Comment by itsdivyanshjain** [comment]
Hey @aman566 , this fix works only for python 3.9.0 not for 3.9.1 and 3.9.2, its show error `[Errno 2] No such file or directory: b'liblibc.a`(after installing scapy module). 

https://stackoverflow.com/questions/65410481/filenotfounderror-errno-2-no-such-file-or-directory-bliblibc-a

Above link mentioned temporary solution regarding this, also pycurl is having similar issues in windows, it work well for python 3.8 but not for python_version > 3.9. I think we should wait for official library support for python_version>3.9 until then we should support now only till < python 3.9.

**Comment by aman566** [comment]
Hello @itsdivyanshjain .Yes, pycurl is having issues. Regarding Scapy, you are correct. For 3.9.1 onwards this doesn't work.

**Comment by itsdivyanshjain** [comment]
we should wait for pycurl support for python 3.9

In regards to scapy, it showing different error to different OS, also i have now tried running python 3.9.2 in docker containers it works completely fine(scapy need to install).

**Comment by aman566** [comment]
Yes you are right

**Comment by Rohan-Salwan** [comment]
Same issue in python 3.8.5

**Comment by itsdivyanshjain** [comment]
@Rohan-Salwan @securestep9 

yes, this `port_scan` module affecting python version 3.8.5 (all python3 versions) now, but by merging this PR#400 this issue can be solved(i have tested out this on docker ubuntu image too and it's work fine). Also, PR #400 doesn't solve the issue for python>3.9.1.
