### ISSUE TITLE
Spanish language is missing 25 keys

### ISSUE THREAD

**Issue by FerreiraEnzoA** [OWASP/Nettacker#436]
Spanish language isn't up-to-date. Some keys (25) are missing in Spanish in comparison to English (default language of this project). When I was adding the Brazilian Portuguese (a PR) I realized this issue.

**Keys missing**
`Invalid_whatcms_api_key`, `searching_whatcms_database`, `whatcms_monthly_quota_exceeded`, `Invalid_shodan_api_key`, `shodan_api_key`, `shodan_results_found`, `shodan_results_not_found`, `shodan_plan_upgrade`, `searching_shodan_database`, `graphql_inspection`, `graphql_inspection_console`, `graphql_console_not_found`, `API_cert`, `API_cert_key`, `api_cert`, `api_cert_key`, `wrong_values`, `using_shodan_query_override`, `invalid_database`, `database_connection_failed`, `fuzzer_no_response`, `summary_report`, `file_saved`, `no_event_found`, `invalid_json_type_to_db`

**Comment by securestep9** [comment]
thanks, can you please submit a PR for Spanish messages as well. The project team is currently working on v0.0.3 which is a big re-write and your PRs will will be reviewed & merged after the new core is ready

**Comment by Ali-Razmjoo** [comment]
i merged your pr, thanks.
