### ISSUE TITLE
Error of execution Nettacker

### ISSUE THREAD

**Issue by tXambe** [OWASP/Nettacker#449]
Hello,

When I run the script I have this error

pip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed!

But this packet is installed
_________________
**OS**: 
VERSION="2021.3"
VERSION_ID="2021.3"
VERSION_CODENAME="kali-rolling"
Linux 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-4kali1 (2021-08-09) x86_64 GNU/Linux

**OS Version**: `x`

**Python Version**: Python 3.9.7

A greeting and thanks

**Comment by itsdivyanshjain** [comment]
Try this command `pip3 install -r requirements.txt` and then run the script again. If it still causing same error try to follow mention steps in this wiki https://github.com/OWASP/Nettacker/wiki/Installation

**Comment by murtazakan** [comment]
I removed the dependency check code lines in the nettacker.py script cause all my requirements were met (both apt and pip), still the nettacker doesn't do anything... Will let you know when i find the bug

**Comment by aman566** [comment]
Hello @murtazakan Can you please more precise about when you say "Nettacker doesn't do anything"
I mean what commands did you tried

**Comment by murtazakan** [comment]
@aman566 

`[2021-09-11 05:28:15][+] Nettacker engine started ...
[2021-09-11 05:28:15][+] 45 modules loaded ...
[2021-09-11 05:28:15][+] regrouping targets based on hardware resources!
[2021-09-11 05:28:15][+] Removing old database record for selected targets and modules.                                                                           
[2021-09-11 05:28:15][+] starting 1 process(es).
`
This is the output after removing dependency check... i kept the computer on for a while.. but no scanning or checks happen on the target site...

**Comment by itsdivyanshjain** [comment]
you need to use command `-module all` or `-m all`. when you use profile(it is grouping of similar templates like wordpress, scan, vuln...), for that you can use command `--profile scan` or view all options for profiles using `python nettacker.py --help`

**Comment by itsdivyanshjain** [comment]
add `--verbose` to above command check and if you can see output(if response are visible to terminal that means nettacker is attempting request but not found anything yet) .  `--profile all` is a aggressive scan, try to use specific modules/profiles using `-m module_name` or  `--profile vuln`.

**Comment by murtazakan** [comment]
ok, thanks guys, seems like its the problem with the target site... i added `--verbose` and it is saying something like this and been stuck here...

[2021-09-11 15:21:20][+] process-1|admin_scan|example.com|module-thread 14/44|request-thread 1082/2344| all conditions failed
[2021-09-11 15:21:20][+] {"headers": {"User-Agent": "Nettacker 0.0.3 TRES - https://github.com/OWASP/Nettacker"}, "url": "http://example.com:80/sshadmin/", "method": "get", "response": {"condition_type": "or", "conditions_results": []}}  

I will need to learn some more before proceeding ahead...

To answer the original question, my suggestion would be to edit the nettacker.py and replace with following code only if all your requirements are met.. its more of a hack not a solution:

`
# if dependencies and OS requirements are match then load the program
from core.parse import load
load()  # load and parse the ARGV
# sys.exit(main())`
`

**Comment by Ali-Razmjoo** [comment]
Hi @murtazakan,

I recommend you use docker to make sure all dependencies are working fine. If you don't want to use that, just make sure you use the same python and pip version. Both must be version 3+. To confirm the pyDNS is installed, you can check in your python3 console.

```
x@MAC-Nettacker % python3             
Python 3.9.7 (default, Sep  3 2021, 12:37:55) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import DNS
>>> 

```
