### ISSUE TITLE
KeyError: 'error_platform'

### ISSUE THREAD

**Issue by robox404** [OWASP/Nettacker#505]
PS C:\Users\robox\Nettacker> python nettacker.py  -h

   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.3
  \____/   \/  \/_/    \_\_____/|_|     TRES
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/OWASP       |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  z3r0d4y.com            | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|

Traceback (most recent call last):
  File "nettacker.py", line 12, in <module>
    check_dependencies()  # check for dependencies
  File "C:\Users\robox\Nettacker\core\compatible.py", line 96, in check_dependencies
    die_failure(messages("error_platform"))
  File "C:\Users\robox\Nettacker\core\alert.py", line 41, in messages
    return message_cache[str(msg_id)]
KeyError: 'error_platform'
PS C:\Users\robox\Nettacker>
_________________
**OS**: `windows`
**OS Version**: `10`
**Python Version**: `Python 3.8.8`

**Comment by itsdivyanshjain** [comment]
@robox404 Windows platform is no longer supported by Nettacker. Try to run this tool using docker if you want to run on windows or run it on Linux.
