### ISSUE TITLE
Contribute to Language Libraries

### ISSUE THREAD

**Issue by EFFLUX110** [OWASP/Nettacker#509]
Hey, I saw that in [en.yaml file](https://github.com/OWASP/Nettacker/blob/master/lib/messages/en.yaml) and [hi.yaml file](https://github.com/OWASP/Nettacker/blob/master/lib/messages/hi.yaml) some keywords/lines are missing.
I think we should modify it for better user experience.
One more thing, I guess Windows platform is no longer supported by Nettacker so we should remove the word ['Windows' in `error_platform` key](https://github.com/OWASP/Nettacker/blob/master/lib/messages/hi.yaml#L56).

@Ali-Razmjoo @securestep9 
 If you found this as a valid issue, then I would like to take up this issue for hi.yaml and en.yaml .

**Comment by Ali-Razmjoo** [comment]
this issue is fixed now, thanks.
