### ISSUE TITLE
Having nettacker in the PATH

### ISSUE THREAD

**Issue by tristanlatr** [OWASP/Nettacker#526]
Right now the issue is that the installation directory is totally arbitrary and the install instructions doesn't prescribe to create a symlink in a directory that is accessible in the PATH. 

I'de propose to add the required steps in the installation docs such that Nettacker would be installed in `/opt/Nettacker/` and a symlink `/usr/local/bin/nettacker` is created. 

So the "Install Requirements" section would read as follows
```
git clone https://github.com/OWASP/Nettacker.git /opt/
cd /opt/Nettacker/
apt-get update
apt-get install -y < requirements-apt-get.txt
pip3 install --upgrade pip
pip3 install -r requirements.txt
pip3 install -r requirements-dev.txt
ln -s /opt/Nettacker/nettacker.py /usr/local/bin/nettacker
```

With the note: This will install Nettacker under `/opt/Nettacker/` and create a symlink in `/usr/local/bin/`. Feel free to adjust this to your needs. 

#525 needs to merged for that to work.

**Comment by dhirensr** [comment]
if the user wants it they can cd and install it right? why do you think we need to mention change directory command explicitly?

**Comment by tristanlatr** [comment]
It’s good to propose a standard place, Such that we can say: “the regular installation directory for nettacker is /opt/nettacker”. And a symlink in the path is generally created. Now, there is absolutely no rules about it. It’s really just about having a symlink in the PATH…

**Comment by tristanlatr** [comment]
This could also be done by packaging nettacker with a setup.py.

**Comment by tristanlatr** [comment]
@dhirensr do you think it would be possible to package nettacker such that we can have an entrypoint in the PATH ? 

Thanks

**Comment by MrImmortal09** [comment]
Hey, There, Can I start Working on this issue, also can you pls assign me.

**Comment by MrImmortal09** [comment]
@dhirensr @tristanlatr

**Comment by securestep9** [comment]
This issue will be resolved in the updating PYPI package release as part of the major refactoring by the maintainers
