### ISSUE TITLE
socket.py file name must be changed.

### ISSUE THREAD

**Issue by Mrinank-Bhowmick** [OWASP/Nettacker#558]
[socket.py](https://github.com/OWASP/Nettacker/blob/master/core/module_protocols/socket.py) file name must be change to other name like `Socket.py` with capital 'S' or `SockeT.py` which should not conflict when some developers are making other python file in [module_protocol](https://github.com/OWASP/Nettacker/tree/master/core/module_protocols) folder which may use inbuild socket module in other python libraries. 

Your prompt response will be highly appreciated.

_________________
**OS**: `x`

**OS Version**: `x`

**Python Version**: `x`

**Comment by MrinankBhowmick** [comment]
When I am importing [poplib](https://github.com/MrinankBhowmick/Nettacker/blob/module/core/module_protocols/pop3.py#L5) module in another file : --> my code [here](https://github.com/MrinankBhowmick/Nettacker/blob/module/core/module_protocols/pop3.py) , by mistake python is pointing the [`socket.py` file here](https://github.com/MrinankBhowmick/Nettacker/blob/module/core/module_protocols/socket.py) which is present in `module_protocols` folder and showing circular import error.

screenshot : 
[![Screenshot-2022-04-18-163101.jpg](https://i.postimg.cc/XNtQtQn5/Screenshot-2022-04-18-163101.jpg)](https://postimg.cc/DmdrXQJf)
