### ISSUE TITLE
packaging issue

### ISSUE THREAD

**Issue by LiteEagle262** [OWASP/Nettacker#573]
Please describe the issue or question and share your OS and Python version.

SystemExit: [1;31m[X] [1;33mpip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed![0m

ive un installed and re installed the package but its still saying that its not installed
_________________
**OS**: `Windows 10`

**OS Version**: `Version	10.0.19043 Build 19043`

**Python Version**: `3.9.2`

**Comment by itsdivyanshjain** [comment]
Windows is no longer supported, still you can run this using docker or using Linux based OS.

**Comment by securestep9** [comment]
@LiteEagle262 if you wish to use Nettacker on Windows please use version 0.0.2: https://github.com/OWASP/Nettacker/releases/tag/0.0.2
