### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Sajeeshab** [OWASP/Nettacker#580]
#Installation Issue :-

./nettacker.py -h                          
[X] pip3 install -r requirements.txt ---> requests==2.26.0 not installed!

_________________
OS : Kali Linux 

OS Version
------------------------
VERSION="2022.3"
VERSION_ID="2022.3"
VERSION_CODENAME="kali-rolling

5.18.0-kali5-amd64

Python Version : Python 3.10.5

**Comment by Mrinank-Bhowmick** [comment]
Run 
pip3 install -r requirements.txt 
on your terminal .
