### ISSUE TITLE
creating pyproject.toml file

### ISSUE THREAD

**Issue by kailashchoudhary11** [OWASP/Nettacker#633]
Setting up a pyproject.toml file for the project

**Comment by securestep9** [comment]
@AtmegaBuzz Getting Error: [tool.poetry] section not found in pyproject.toml !

**Comment by prbhtkumr** [comment]
hey, is this issue still open? i want to start participating in the project and am looking for a starting point.

**Comment by securestep9** [comment]
There is a major code refactoring ongoing right now with additional work done as part of Google Summer of Code 2024. We will include your suggestions once the new version of Nettacker with refactored codebase is released at the end of August

**Comment by arkid15r** [comment]
Implemented in https://github.com/OWASP/Nettacker/pull/863
