### ISSUE TITLE
gcc and libssl-dev not found in docker-compose build 

### ISSUE THREAD

**Issue by Existential-Kernel** [OWASP/Nettacker#648]
after doing the quick setup command I did that's shown in the README, i get 2 errors in the 7th step (out of 12) in the docker-compose:
```
E: Unable to locate package libssl-dev
E: Unable to locate package gcc
```
_________________
**OS**: `Fedora 36`

**OS Version**: `6.1.7-100.fc36.x86_64`

**Python Version**: `3.10.9`

**Comment by itsdivyanshjain** [comment]
directly use this command `apt install libssl-dev gcc` and re run the script and let me know is it working or not.

**Comment by Existential-Kernel** [comment]
It does, but i had to add some extra things to the Dockerfile to actually make it work. Idk if you want to implement the extra docker commands to the project but i'll share it to you anyway:
```
RUN apt-get update -y && apt-get dist-upgrade -y
RUN sed -i -e 's/archive.ubuntu.com\|security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
RUN apt install gcc libssl-dev -y
```
