### ISSUE TITLE
mac [X] pip3 install -r requirements.txt ---> py3DNS==3.2.1 not installed!

### ISSUE THREAD

**Issue by dead5nd** [OWASP/Nettacker#659]
Please describe the issue or question and share your OS and Python version.
_________________
**OS**: `x`
mac

**OS Version**: `x`
<img width="321" alt="image" src="https://user-images.githubusercontent.com/29460919/225506344-27b6bfc6-90e4-4bb0-8f57-d6b5fc024fcb.png">

**Python Version**: `x`
3.8 ,3.9
<img width="533" alt="image" src="https://user-images.githubusercontent.com/29460919/225506372-88f5a31b-3b19-4545-b57b-42ec594e0618.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/29460919/225506396-031fbb7f-41c0-4d88-a074-fcb52cf987ae.png">

In mac，I have installed py3dns, but when I run it, the error shows that it is not installed.

**Comment by securestep9** [comment]
you need to upgrade your Python to the latest version or  at least version 3.9.2 - please check if this fixes your problem

**Comment by dead5nd** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/29460919/225808994-42b1a882-434a-41ec-92ff-1b30e4be2578.png">

**Comment by securestep9** [comment]
try this please (in Nettacker folder): 

```
pip3 uninstall py3DNS
pip3 install setuptools wheel
pip3 install -r requirements.txt

```

**Comment by securestep9** [comment]
closed as no response - assume the advice has worked (tested locally)
