### ISSUE TITLE
Module http form brute not available

### ISSUE THREAD

**Issue by pradeepjairamani** [OWASP/Nettacker#69]
Please Describe the issue or question and share your OS and Python version.
_________________
**OS**: `Linux'

**OS Version**: `Linux Ubuntu`

**Python Version**: `2.7.3

![screenshot_18](https://user-images.githubusercontent.com/24669027/37253503-8ba34f1a-2558-11e8-9f68-87c7106950c3.png)
`

**Comment by shaddygarg** [comment]
This issue was due to a change in the language library. I will send a fix soon.

**Comment by Ali-Razmjoo** [comment]
Hey,

Thank you, the merged PR fixed the issue.

Best Regards.

**Comment by pradeepjairamani** [comment]
This is the job result of current commit, Please Reopen this issue as it is not resolved.

Best Regards
Pradeep Jairamani

![screenshot_2](https://user-images.githubusercontent.com/24669027/37425929-21b27d70-27eb-11e8-8693-1f5f328b7495.png)

**Comment by JeckyOH** [comment]
I pulled an request to solve this issue.
Just because the compatibility of HTMLParser and cookiejar modules between Python 2 and 3.

**Comment by Ali-Razmjoo** [comment]
Hello @JeckyOH,

Thank you for your contribution, I'll check your PR and get back to you soon.

Regards.

**Comment by mzfr** [comment]
@Ali-Razmjoo @securestep9 It looks like this issue is fixed.

**Comment by aman566** [comment]
The current http_form_brute is not giving correct results 
![image](https://user-images.githubusercontent.com/32503192/88471217-0cdffe80-cf24-11ea-825b-123450cd5c13.png)

I tried fixing in #305 

![image](https://user-images.githubusercontent.com/32503192/88471227-431d7e00-cf24-11ea-9348-3034b5fca093.png)
