### ISSUE TITLE
A better HTML report

### ISSUE THREAD

**Issue by Ali-Razmjoo** [OWASP/Nettacker#7]
Hello everyone,

Right now the framework supports three types of outputs. `JSON`, `Text` and `HTML`. the HTML can handle a graph also. `d3_tree_v1_graph`, `d3_tree_v2_graph`, `jit_circle_v1_graph`. But it's not nice at all! I glad if someone could help me with a better HTML output.

To see how the framework is creating an HTML report, check the `core/log.py`.

Let me know if there is any question.

Regards.

**Comment by omdmhd** [comment]
Hello ,
Do you have any specific idea for a better HTML output ?
Don't you think that it is better that all kind of graphs having the same HTML output ?
I suggest `d3_tree_v1_graph,d3_tree_v2_graph` be like ` jit_circle_v1_graph `

**Comment by Ali-Razmjoo** [comment]
Hello,

I am like those HTML templates, so at the beginning, I just used those templates temporary to improved them later! As you can see in the issues (enhancements) we are working on new modules to provide a better scanner with more details, but due we are still in core optimization phase, we cannot develop modules much!

BTW, It's best to use the same HTML template that we want to use in explorer system #8. (something like ivre, censys or shodan).

let me know if you have any idea or you'd like to work on this.

Regards.

**Comment by omdmhd** [comment]
Hello,
Well,surely i like to work on this project . and doesn't matter which part  .
but if we are going to make something like [shodan](https://www.shodan.io/) or  [censys.io](https://censys.io/) . I think it is necessary to first create local database and then we improve the HTML template to be something like [censys.io](https://censys.io/) .

**Comment by Ali-Razmjoo** [comment]
Hi @omdmhd ,

You are right about the local database should be the first, so it's best you work on other parts at the moment. (I'm working on API). it's best if someone could re-check language [libraries](https://github.com/viraintel/OWASP-Nettacker/tree/master/lib/language) and sync others with English library (even with the google translate).

I may recommend you to work on developing new module (even simple). Documents are available on the wiki.

Regards.

**Comment by Ali-Razmjoo** [comment]
@shaddygarg could you work on this as well?

**Comment by shaddygarg** [comment]
Sure Ali, I will have a look into it and will let you know if I find a better alternative and a better design.

**Comment by Ali-Razmjoo** [comment]
it could be better tho but let's close this for now, we can have new design in next version.
