### ISSUE TITLE
Hey Torsten.  What sort of documents are you specifically referring to?  Are you meaning simply a place to store non-web-specific (not md, html) files from which others could reference the files?  Some of this exists already with regard to images which can be used in projects, etc.

### ISSUE THREAD

**Issue by MihailGalkin123** [OWASP/Nettacker#724]
Hey Torsten.  What sort of documents are you specifically referring to?  Are you meaning simply a place to store non-web-specific (not md, html) files from which others could reference the files?  Some of this exists already with regard to images which can be used in projects, etc.

Also, the ability to add files to the www-community repository is open to all.  There is a folder called assets in that repository and folders under that for files and images.

_Originally posted by @hblankenship in https://github.com/OWASP/owasp.github.io/issues/21#issuecomment-556927413_

**Comment by securestep9** [comment]
Not a real issue - copy paste of an issue from OWASP Github dated 2019
