### ISSUE TITLE
How can i remove all the hosts and the scans i've done?

### ISSUE THREAD

**Issue by ErtyDess** [OWASP/Nettacker#765]
Please describe the issue or question and share your OS and Python version.
_________________
OS: x
Ubuntu
OS Version: x
22.04.2 LTS
Python Version: x
Python 3.10.12

How can i remove all the hosts and the scans i've done? to clear all basically

**Comment by securestep9** [comment]
All Nettacker data is stored in the .data folder where you will find the nettacker.db sql lite database , the results and the tmp folder.

you can simply delete the ".data" folder to clear all history (or rname it to something else in case you want to keep it) and re-start Nettacker - it will create a fresh ".data" folder with blank database

**Comment by ErtyDess** [comment]
Thank you !!

**Comment by ErtyDess** [comment]
@securestep9 actually i found out that i need to remove only the contet od the .data folder otherwise it won't work anymore, removing only the contents insede the folder works

**Comment by ErtyDess** [comment]
EDIT: For everyone that needs to do it, DON'T remove the whole directory because it won't work anymore, instead remove only the content inside it and do docker compose down and then restart it with docker compose up -d
