### ISSUE TITLE
Correct profile name 'invati_ics' in ivanti_ics_cve_2023_46805_vuln module

### ISSUE THREAD

**Issue by aminutolo** [OWASP/Nettacker#802]
Correct profile name 'invati_ics' by changing it to 'ivanti_ics' in ivanti_ics_cve_2023_46805_vuln module
_________________
**OS**: `docker image`

**OS Version**: `x`

**Python Version**: `Python 3.11.6`

**Comment by securestep9** [comment]
merged, thank you!
